name: dbt_retail
version: '1.0.0'
config-version: 2

profile: dbt_retail

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_retail:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
