{% macro sport_category(column) %}
    CASE
        WHEN {{ column }} IS NULL OR TRIM({{ column }}) = '' OR LOWER(TRIM({{ column }})) = 'none'
            THEN 'Uncategorized'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%lifestyle%'
            THEN 'Lifestyle'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%soccer%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%football%'
            THEN 'Soccer & Football'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%basketball%'
            THEN 'Basketball'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%running%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%track%'
            THEN 'Running'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%training%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%gym%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%workout%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%studio%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%strength%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%hiit%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%high-intensity%'
            THEN 'Training & Gym'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%golf%'
            THEN 'Golf'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%tennis%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%padel%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%pickleball%'
            THEN 'Racquet Sports'
        WHEN SPLIT_PART({{ column }}, '|', 1) ILIKE '%outdoor%'
          OR SPLIT_PART({{ column }}, '|', 1) ILIKE '%hiking%'
            THEN 'Outdoor'
        ELSE 'Other Sports'
    END
{% endmacro %}
